name: uas_mp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.4.0
  cupertino_icons: ^1.0.8
  flutter_epub_viewer: ^1.2.0
  path_provider: ^2.1.5
  firebase_storage: ^12.4.1
  file_picker: ^8.1.7
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  image: ^4.5.2
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdf/book1.pdf
    - assets/pdf/book2.pdf
    - assets/pdf/book3.pdf
    - assets/pdf/book4.pdf
    - assets/epub/book1.epub
    - assets/epub/book2.epub
    - assets/epub/book3.epub
    - assets/watermark.png
